# Generated by Django 5.2.1 on 2025-05-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0002_alter_task_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
